### ISSUE TITLE
Schemas and Relationships

### ISSUE THREAD

**Issue by Cfeusier** [OceanOracles/OceanOracles#11]
Freeze MVP schema designs

**Comment by Cfeusier** [comment]
![Schema Design CF 0.0.1](https://s3.amazonaws.com/uploads.hipchat.com/121019/1500922/0kWNRYDu0VK0KoD/Screen%20Shot%202015-01-21%20at%206.17.26%20PM.png)

**Comment by ekeric13** [comment]
http://stackoverflow.com/questions/25101386/many-to-many-relationship-with-nosql-mongodb-and-mongoose

good stackoverflow post on relationships in mongoose
