### ISSUE TITLE
Practice Demo Presentation

### ISSUE THREAD

**Issue by Cfeusier** [OceanOracles/OceanOracles#117]

**Comment by ekeric13** [comment]
1. (showing the website) what the product is -raghu
2. why we chose the tech stack we did. how we used the product backlog. github workflow. work schedule. mvp goals. - eric
3. (going through the code) difficulties building the product and aritechetural decisions we made. things we wished we could have done that next team can do (voting) - clark

**Comment by Cfeusier** [comment]
This looks good, but not sure that (2) should include the tech stack... that seems to be part of (3).

1. product
2. process
3. tech

is how you seem to have set it up.

**Comment by ekeric13** [comment]
Yeah, i saw the tech stack being part of both parts. 
It is part of the process of where we wanted the app to go and be. It would just be touched on briefly how we wanted to do mongo, express, backbone, angular as it fit our learning goals and the app's needs.
I saw you touching on it on more of the implementation level part. Like how we determined to do routing on the client side and have the templates be on the client side.

obviously this is just what i imagine we will talk about. if it doesn't seem to be natural to talk about when presenting in our practice walkthrough then i will not bring it up.

I forgot to add. When i will be talking i should be going through the waffle, and our github repo.

**Comment by ekeric13** [comment]
we might want to end our presentation with a couple reasons why they might want to take over:
1. well defined new features to implement (voting, sorting, commenting)
2. no bugs and finely architected backend with modularized front end so you don't have to spend your time fixing bad code or dealing with small hacks.
3. want to work with backbone and understand how a good backbone app might set up client side routing and templating.
etc.
