### ISSUE TITLE
Wireframe + Aesthetics

### ISSUE THREAD

**Issue by d4ncer** [OceanOracles/OceanOracles#20]

**Comment by d4ncer** [comment]
Initial Wireframe. Drilled down on typography / type scale / colours as well. Will share during scrum tomorrow morning. 

All feedback appreciated.

![v0 0 1-master](https://cloud.githubusercontent.com/assets/1840377/5851530/b0557046-a22e-11e4-9a4e-1a49d37ad6d6.png)

**Comment by d4ncer** [comment]
Views:
- Landing (not signed in)
- Landing
- Sign in / Log in
- Guide
- Edit guide (signed in)

Am I missing any?

**Comment by Cfeusier** [comment]
Ragz, are the landing (not signed in) and signed in the same?

**Comment by d4ncer** [comment]
Almost, there's no sign in / log in button on top and there may be a "create guide" button instead. Haven't decided on that yet, any thoughts?

**Comment by d4ncer** [comment]
![guide create](https://cloud.githubusercontent.com/assets/1840377/5864397/be2cf9b8-a2a7-11e4-9b18-7e0f66a8b80f.png)
![guide edit](https://cloud.githubusercontent.com/assets/1840377/5864398/be598898-a2a7-11e4-9b0a-e2a1b0338734.png)
![index logged in](https://cloud.githubusercontent.com/assets/1840377/5864399/be742108-a2a7-11e4-9a43-c4fb2921f5dc.png)
![index](https://cloud.githubusercontent.com/assets/1840377/5864400/be78910c-a2a7-11e4-971e-5dcc2b54cb34.png)
![signup-login](https://cloud.githubusercontent.com/assets/1840377/5864401/be794a66-a2a7-11e4-9c86-b3d131fd10bd.png)

**Comment by d4ncer** [comment]
Added wireframes for all the views. In order they are:

- Guide
- Guide (edit/create)
- Home (logged in)
- Home (not logged in)
- Sign up / Log in

@Cfeusier @ekeric13 feedback appreciated!
