### ISSUE TITLE
Move model responsibilities out of views

### ISSUE THREAD

**Issue by Cfeusier** [OceanOracles/OceanOracles#65]

**Comment by Cfeusier** [comment]
e.g., the signup view shouldn't be hitting the server endpoints directly -- that should be a responsibility of the model.

**Comment by ekeric13** [comment]
I think raghu is working on this...

**Comment by ekeric13** [comment]
Let's discuss in the hangout

**Comment by ekeric13** [comment]
okay, i think i get what you are saying. put the ajax request into the model.

**Comment by ekeric13** [comment]
i will say though in the wine cellar tutorial he was doing what we have in the views
https://github.com/ccoenraets/backbone-cellar/blob/master/bootstrap/js/views/winedetails.js
line 61
